api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from api import views

urlpatterns = [
    url(r'^data$', views.getData, name='data_api'),
    url(r'^(?P<judge_id>\d+)/(?P<claim_id>\d+)$', views.setClaimToJudge, name='set_claim_to_judge')
]

judge/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from judge import views

urlpatterns = [
    url(r'^claims/$', views.claims, name='judge_claims'),
    url(r'^claim-facts/(?P<claim_id>\d+)$', views.claim_facts, name='claim_facts'),
    url(r'^change_status/(?P<claim_id>\d+)$', views.change_claim_status, name='claim_change_status'),
    url(r'claims/archive$', views.list_archive_claims, name='judge_archive_claims'),
    url(r'^claim/(?P<claim_id>\d+)$', views.claim_page, name='claim_page'),
]

robo/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from robo import settings

urlpatterns = [
                  url(r'^administrator/', include('administrator.urls')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^user/', include('user.urls')),
                  url(r'^', include('user.urls')),
                  url(r'^manager/', include('manager.urls')),
                  url(r'^judge/', include('judge.urls')),
                  url(r'^api/', include('api.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

judge/models.py
from django.db import models

# Create your models here.

user/models.py
import datetime
from datetime import datetime as date_now

import django
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


# Create your models here.
class File(models.Model):
    name = models.CharField(max_length=128)
    file = models.FileField(upload_to='docs/')

class ClaimFile(models.Model):
    name = models.CharField(max_length=128)
    file = models.FileField(upload_to='claims/')

class Classification(models.Model):
    def __str__(self):
        return self.name

    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, unique=True)
    enable = models.BooleanField(default=True)
    difficult = models.PositiveSmallIntegerField(default=1)

class Role(models.Model):
    ROLE_MANAGER = 1
    ROLE_JUDGE = 2
    ROLE_ADMIN = 3

    def __str__(self):
        return self.name

    name = models.CharField(max_length=256, unique=True)
    sys_name = models.CharField(max_length=256, unique=True)


class Profile(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User)


class Employee(models.Model):
    def __str__(self):
        return ' / '.join([self.fio, self.role.name])

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    user = models.OneToOneField(User, verbose_name="Пользователь")
    fio = models.CharField(max_length=256, verbose_name='ФИО')
    phone = models.CharField(max_length=256, verbose_name='Телефон')
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True, verbose_name='Роль')
    classification = models.ManyToManyField(Classification, blank=True, null=True, verbose_name='Классификация')


class StatusClaim(models.Model):
    def __str__(self):
        return self.name

    STATUS_ACCEPT = 1
    STATUS_RETURN = 2
    STATUS_ARCHIVE = 3
    STATUS_STOP = 4
    STATUS_REJECT = 5
    STATUS_GRANT = 6
    STATUS_GRANT_PARTIALLY = 7
    STATUS_PROCESSING = 8

    @staticmethod
    def getClaimNotFinishedStatuses():
        return [StatusClaim.STATUS_STOP, StatusClaim.STATUS_ACCEPT]

    name = models.TextField(max_length=256)


class Claim(models.Model):
    def __str__(self):
        return self.name

    user = models.ForeignKey(Profile, null=True)
    judge = models.ForeignKey(Employee, blank=True, null=True)
    status = models.ForeignKey(StatusClaim, blank=True, null=True, default=StatusClaim.STATUS_PROCESSING, editable=False)

    __previous_judge_id = None

    def __init__(self, *args, **kwargs):
        super(Claim, self).__init__(*args, **kwargs)
        self.__previous_judge_id = self.judge_id

    # Сохранение даты назначения на судью
    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.judge_id != None and self.judge_id != self.__previous_judge_id:
            self.assign_date = date_now.now().date()

        super(Claim, self).save(force_insert, force_update, *args, **kwargs)
        self.__previous_judge_id = self.judge_id

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,11}$',
                                 message="Факс должен иметь формат: '+999999999'. До 11 цифр и символ +")

    name = models.CharField(max_length=256,verbose_name='Наименование заявления')
    court = models.CharField(max_length=256,verbose_name='Арбитражный суд')
    plaintfill = models.CharField(max_length=256,verbose_name='Представитель')
    address = models.CharField(max_length=256,verbose_name='Адрес')
    fax = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday = models.DateField(verbose_name='Дата рождения')

    plaintfill_representative = models.CharField(max_length=256,verbose_name='Представитель')
    address_representative = models.CharField(max_length=256,verbose_name='Адрес')
    fax_representative = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email_representative = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday_representative = models.DateField(verbose_name='Дата рождения')

    defendant = models.CharField(max_length=256,verbose_name='Представитель')
    address_defendant = models.CharField(max_length=256,verbose_name='Адрес')
    fax_defendant = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email_defendant = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday_defendant = models.DateField(verbose_name='Дата рождения')

    assign_date = models.DateField(blank=True, null=True)

    date = models.DateField(default=django.utils.timezone.now,verbose_name='Дата')
    files = models.ManyToManyField(File,verbose_name='Приложение')
    claim_file = models.ForeignKey(ClaimFile, blank=True, null=True)

    claim_body = models.TextField(verbose_name='Исковое заявление')
    claim_request  = models.TextField(verbose_name='Прошу')

    classification = models.ForeignKey(Classification, blank=True, null=True)


class StatusClaimHistory(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    reason = models.TextField(verbose_name='На основании чего')
    new_status = models.ForeignKey(StatusClaim, null=True, related_name='new_status',verbose_name='Новый статус')
    old_status = models.ForeignKey(StatusClaim, null=True, related_name='old_status',verbose_name='Текущий статус')

    claim = models.ForeignKey(Claim)


class Setting(models.Model):
    ENABLE_AUTO_CLASSIFICATION = 1
    JUDGE_DAILY_CLAIM_COUNT = 2

    value = models.CharField(max_length=256)

    def getValueById(id):
        return Setting.objects.filter(id=id).get().value

judge/views.py
import os

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import render, redirect
from docx import Document

from judge.tools import getFactsByClaim, getFactsClaimsId, getClaimCaseHref
from django.conf import settings

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from user.forms import FirstStatusClaimHistoryForm, SecondStatusClaimHistoryForm, StatusClaimHistoryForm
from user.models import Claim, Employee, Profile, StatusClaim, StatusClaimHistory, Role
from user.tools import checkEmployee
from django.db.models import Q


@login_required(login_url='login_page')
def claims(request):
    if checkEmployee(request.user, Role.ROLE_JUDGE):
        if request.method == 'GET':
            try:
                u = Employee.objects.get(user=request.user)
            except ObjectDoesNotExist:
                return redirect(to='employees')
            claims = Claim.objects.filter(judge=u).filter(~Q(status_id=StatusClaim.STATUS_ARCHIVE))
            return render(request, 'claims.html', {'claims': claims})
    else:
        return JsonResponse({'error': 'permission denied'})


@login_required(login_url='login_page')
def list_archive_claims(request):
    if checkEmployee(request.user, Role.ROLE_JUDGE):
        if request.method == 'GET':
            try:
                u = Employee.objects.get(user_id=request.user)
            except ObjectDoesNotExist:
                return redirect(to='employees')
            claims = Claim.objects.filter(judge=u).filter(status_id=StatusClaim.STATUS_ARCHIVE)
            return render(request, 'claims.html', {'claims': claims})
    else:
        return JsonResponse({'error': 'permission denied'})


@login_required(login_url='login_page')
@csrf_exempt
def change_claim_status(request, claim_id):
    request_type = request.GET.get('request_type')
    claim = Claim.objects.get(id=claim_id, judge=Employee.objects.get(user_id=request.user))
    claim_history = StatusClaimHistory()
    claim_history.claim_id = claim.id
    if claim == None:
        return JsonResponse({'status': 'error'})
    if request.method == "POST":
        form = StatusClaimHistoryForm(request.POST, instance=claim_history)
        if form.is_valid():
            form.instance.old_status_id = claim.status_id
            claim.status_id = form.instance.new_status_id
            form.instance.claim_id = claim.id
            form.save()
            claim.save()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'error', 'message': str(form.errors.as_ul())})
    elif request.method == "GET":
        if (request_type == '1'):
            form = FirstStatusClaimHistoryForm(instance=claim_history)
            string = 'заявлению'
        else:
            form = SecondStatusClaimHistoryForm(instance=claim_history)
            string = 'делу'
        form.claim = claim
        form.old_status = claim.status
        history = StatusClaimHistory.objects.filter(claim_id=claim.id).order_by('date')

        return render(request, 'change_status.html', {'form': form, 'claim': claim, 'history': history ,'string':string})


@login_required(login_url='login_page')
def claim_facts(request, claim_id):
    if checkEmployee(request.user, Role.ROLE_JUDGE):
        if request.method == 'GET':
            empl = Employee.objects.get(user_id=request.user)
            claim = Claim.objects.get(judge=empl, id=claim_id)
            try:
                data = getFactsByClaim(claim.claim_file.name)
            except:
                return render(request, 'connection_error.html')

            return render(request, 'judge_claim_page.html', {'text': data['text'], 'facts': data['annotations']})
    else:
        return JsonResponse({'error': 'permission denied'})


@login_required(login_url='login_page')
def claim_page(request, claim_id):
    # if checkEmployee(request.user, Role.ROLE_JUDGE):
        if request.method == 'GET':
            try:
                empl = Employee.objects.get(user_id=request.user)
                claim = Claim.objects.get(judge=empl, id=claim_id)
            except ObjectDoesNotExist:
                claim = Claim.objects.get(id=claim_id)
            claim_file_path = str(claim.claim_file.file)
            filename, file_extension = os.path.splitext(claim_file_path)
            filepath = os.path.join(settings.MEDIA_ROOT, claim_file_path)
            f = open(filepath, 'rb')
            content = ''
            if (claim.claim_file.name not in getFactsClaimsId()):
                is_mark = False
                if (file_extension == '.docx'):
                    doc = Document(f)
                    fullText = []
                    for para in doc.paragraphs:
                        fullText.append(para.text)
                    content = '\n'.join(fullText)
            else:
                is_mark = True
                content = getClaimCaseHref(claim.claim_file.name)
            claim_history = StatusClaimHistory()
            claim_history.claim_id = claim.id
            form = SecondStatusClaimHistoryForm(instance=claim_history)
            form.old_status = claim.status
            form.new_status = claim.status
            return render(request, 'claim_page.html', {
                'is_mark': is_mark,
                'content': content,
                'form': form,
                'claim': claim
            })

    # else:
    #     return JsonResponse({'error': 'permission denied'})

judge/templates/change_status.html
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Вынесение решения по {{ string }}</h4>
        <p>
            <button id="change_status" class="btn btn-success">Сохранить</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal" >Закрыть</button>
        </p>
        <div id="result">
        </div>
    </div>

    <div class="modal-body">

        {% load bootstrap3 %}
        <form id="change_status_form" method="post" action="{% url 'claim_change_status' claim_id=claim.id %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input name="old_status" id="id_old_status" value="{{ form.old_status.id }}" type="hidden">
        </form>
    </div>
    <div class="modal-header">
        <h4 class="modal-title">История изменения статусов</h4>
    </div>
    <div class="modal-body">

        <table class="table table-bordered table-history">
            <thead>
            <tr>
                <th>Дата</th>
                <th>Новый статус</th>
                <th>Предыдущий статус</th>
                <th>Определение</th>
            </tr>
            </thead>
            <tbody>
            {% for item in history %}
                <tr>
                    <td>{{ item.date }}</td>
                    <td>{{ item.new_status }}</td>
                    <td>
                        {% if item.old_status == None %}
                        Не определено
                    {% else %}
                        {{ item.old_status }}
                    {% endif %}
                    </td>
                    <td>
                        {{ item.reason }}
                    </td>

                </tr>
            {% empty %}
                Статус не менялся
            {% endfor %}


            </tbody>
        </table>


    </div>
</div>
<script type="text/javascript">
    $("#change_status").click(function () {
        var form = $("#change_status_form");
        $.ajax({
            type: "POST",
            url: form.attr('action'),
            data: form.serialize(),
            success: function (response) {
                result_div = $('#result');
                if (response.status == 'success') {
                    location.href = '{% url 'judge_claims' %}';
                } else {
                    result_div.html("<div class='alert alert-danger'>" + response.message + "</div>")

                }

            }
        });
    });
</script>

judge/templates/claim_page.html
{% extends "base.html" %}
{% block title %}Заявление{% endblock %}
{% block content %}
    {% load bootstrap3 %}
    {% load staticfiles %}
    {% if  not is_mark %}
        <div id="casetext" xmlns:border="http://www.w3.org/1999/xhtml">
            {{ content }}
        </div>
    {% else %}
        <iframe src="{{ content }}" width="100%" frameBorder="0" height="1170px" align="left">
        </iframe>
    {% endif %}


    <section class="decision-description">
        <div class="container">
            <div class="row">
                <div class="col-md-1 col-md-offset-10 text-right" style="padding: 20px">
                    {% if user.employee.role.sys_name == 'ROLE_JUDGE' %}
                    <a data-toggle="modal" href="{% url 'claim_change_status' claim.id%}?request_type=2"
                       data-target="#myModal" class="btn btn-appoint"
                       style="height: 45px;line-height: 15px;margin-bottom: 50px;">Вынести<br>вердикт
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">


        </div>
    </div>

    {% block js %}

        <script type="text/javascript">

            function showModal(e, attribute, modal_id) {
                e.preventDefault();
                var url = attribute.attr('href');
                $.get(url, function (data) {
                    $('.modal-dialog').html(data);
                    $('#' + modal_id).modal('show');
                });
            }

            $(document).ready(function () {

                $('[data-toggle="modal"]').click(function (e) {
                    showModal(e, $(this), 'myModal')
                });

            });


        </script>
    {% endblock %}
    <script type="text/javascript">
        $(document).on('click', '.rail_btn', function (e) {
            $(document).find('.rail_btn').removeClass('rail_btn_active');
            $(this).addClass('rail_btn_active');
            $('input[name="new_status"]').val($(this).attr('data-id'));
        });
        $("#change_status").click(function () {
            var form = $("#change_status_form");
            $.ajax({
                type: "POST",
                url: form.attr('action'),
                data: form.serialize(),
                success: function (response) {
                    result_div = $('#result');
                    if (response.status == 'success') {
                        location.href.replace({% url 'judge_claims' %});
                    } else {
                        result_div.html("<div class='alert alert-danger'>" + response.message + "</div>")

                    }

                }
            });
        });
    </script>
{% endblock %}

judge/templates/claims.html
{% extends "base.html" %}
{% block title %}Заявления{% endblock %}
{% block content %}
    {% load staticfiles %}
    <div id="statement-judge" class="tab-pane fade in active">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="tab-content-btn">
                        <a href="{{ request.url }}" class="btn btn-update">
                            Обновить
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <table>
                    <tr class="border_bottom">
                        <td>
                            Название
                        </td>

                        <td class="class cell">
                            Класс
                        </td>
                        <td class="date cell">
                            Дата
                        </td>
                        <td class="status cell">
                            Статус
                        </td>


                    </tr>
                    {% for claim in claims %}
                        <tr class="border_bottom">
                            <td>
                                {% if claim.claim_file.name %}
                                    <a href="{% url 'claim_page' claim.id %}">
                                        Заявление {{ claim.id }}
                                    </a>
                                {% else %}
                                    Заявление {{ claim.id }}
                                {% endif %}
                            </td>

                            <td class="class cell">
                                {% if claim.classification == None %}
                                    Не определено
                                {% else %}
                                    {{ claim.classification }}
                                {% endif %}
                            </td>
                            <td class="date cell">
                                {{ claim.date }}
                            </td>
                            <td class="status cell">
                                {{ claim.status }}
                            </td>
                            {% if claim.status.id != 6  and claim.status.id != 7  and claim.status.id != 5 %}
                                <td class="cross-arrows">
                                    <a data-toggle="modal"
                                       href="{% url 'claim_change_status' claim.id %}?request_type=1"
                                       data-target="#myModal"><img src="{% static 'icon/crossed arrows.svg' %}"></a>
                                </td>
                            {% endif %}

                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">


        </div>
    </div>
    <div class="modal fade" id="view-modal" role="dialog">
        <div class="modal-dialog modal_claim">


        </div>
    </div>
{% endblock %}

{% block js %}

    <script type="text/javascript">

        function showModal(e, attribute, modal_id) {
            e.preventDefault();
            var url = attribute.attr('href');
            $.get(url, function (data) {
                $('.modal-dialog').html(data);
                $('#' + modal_id).modal('show');
            });
        }

        $(document).ready(function () {

            $('[data-toggle="modal"]').click(function (e) {
                showModal(e, $(this), 'myModal')
            });

            $('[data-toggle="modal-view"]').click(function (e) {
                showModal(e, $(this), 'view-modal')
            });
        });


    </script>
{% endblock %}

judge/templates/connection_error.html
<div class="modal-content">
    <div class="modal-header">
        <p>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Закрыть</button>
                <h4 class="modal-title">Ошибка</h4>
        </p>
    </div>
    <div class="modal-body">
        <h5>Сервер извлечения фактов не доступен</h5>
    </div>
</div>

judge/templates/judge_claim_page.html
<div class="modal-content">
    <div class="modal-header">
        <p>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Закрыть</button>
        <h4 class="modal-title">Просмотр заявления</h4>

        </p>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-7">
                <p id="casetext">{{ text }}
                </p>
            </div>
            <div class="col-md-5">
                <div class="facts">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>Тип</th>
                            <th>Текст</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for fact in facts %}
                            <tr>
                                <td>{{ fact.type }}</td>
                                <td>{{ fact.text }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>