administrator/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from administrator import views

urlpatterns = [
    url(r'^employees/$', views.employees, name='employees'),
    url(r'^employees_characteristics/$', views.employees_characteristics, name='employees_characteristics'),
    url(r'^employee_characteristics_create/$', views.employee_characteristics_create, name='employee_characteristics_create'),
    url(r'^employee/update/(?P<employee_id>\d+)$', views.employee_update, name='employee_update'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^classification-list/$', views.classification_list, name='classification_list'),
    url(r'^classification-delete/$',views.classification_delete, name='classification_delete'),
    url(r'^settings/update/(?P<setting_id>\d+)$', views.settings_update, name='settings_update'),
    url(r'^employee/delete/(?P<employee_id>\d+)$', views.employee_delete, name='employee_delete'),
]

api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from api import views

urlpatterns = [
    url(r'^data$', views.getData, name='data_api'),
    url(r'^(?P<judge_id>\d+)/(?P<claim_id>\d+)$', views.setClaimToJudge, name='set_claim_to_judge')
]

robo/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from robo import settings

urlpatterns = [
                  url(r'^administrator/', include('administrator.urls')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^user/', include('user.urls')),
                  url(r'^', include('user.urls')),
                  url(r'^manager/', include('manager.urls')),
                  url(r'^judge/', include('judge.urls')),
                  url(r'^api/', include('api.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models

# Create your models here.
from robo import settings
from user.models import Employee


class EmployeeCharacteristic(models.Model):

    employee = models.ForeignKey(Employee)
    date_start = models.DateField()
    date_finish = models.DateField()
    qualification = models.PositiveSmallIntegerField(default=1)

user/models.py
import datetime
from datetime import datetime as date_now

import django
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


# Create your models here.
class File(models.Model):
    name = models.CharField(max_length=128)
    file = models.FileField(upload_to='docs/')

class ClaimFile(models.Model):
    name = models.CharField(max_length=128)
    file = models.FileField(upload_to='claims/')

class Classification(models.Model):
    def __str__(self):
        return self.name

    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, unique=True)
    enable = models.BooleanField(default=True)
    difficult = models.PositiveSmallIntegerField(default=1)

class Role(models.Model):
    ROLE_MANAGER = 1
    ROLE_JUDGE = 2
    ROLE_ADMIN = 3

    def __str__(self):
        return self.name

    name = models.CharField(max_length=256, unique=True)
    sys_name = models.CharField(max_length=256, unique=True)


class Profile(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User)


class Employee(models.Model):
    def __str__(self):
        return ' / '.join([self.fio, self.role.name])

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    user = models.OneToOneField(User, verbose_name="Пользователь")
    fio = models.CharField(max_length=256, verbose_name='ФИО')
    phone = models.CharField(max_length=256, verbose_name='Телефон')
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True, verbose_name='Роль')
    classification = models.ManyToManyField(Classification, blank=True, null=True, verbose_name='Классификация')


class StatusClaim(models.Model):
    def __str__(self):
        return self.name

    STATUS_ACCEPT = 1
    STATUS_RETURN = 2
    STATUS_ARCHIVE = 3
    STATUS_STOP = 4
    STATUS_REJECT = 5
    STATUS_GRANT = 6
    STATUS_GRANT_PARTIALLY = 7
    STATUS_PROCESSING = 8

    @staticmethod
    def getClaimNotFinishedStatuses():
        return [StatusClaim.STATUS_STOP, StatusClaim.STATUS_ACCEPT]

    name = models.TextField(max_length=256)


class Claim(models.Model):
    def __str__(self):
        return self.name

    user = models.ForeignKey(Profile, null=True)
    judge = models.ForeignKey(Employee, blank=True, null=True)
    status = models.ForeignKey(StatusClaim, blank=True, null=True, default=StatusClaim.STATUS_PROCESSING, editable=False)

    __previous_judge_id = None

    def __init__(self, *args, **kwargs):
        super(Claim, self).__init__(*args, **kwargs)
        self.__previous_judge_id = self.judge_id

    # Сохранение даты назначения на судью
    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.judge_id != None and self.judge_id != self.__previous_judge_id:
            self.assign_date = date_now.now().date()

        super(Claim, self).save(force_insert, force_update, *args, **kwargs)
        self.__previous_judge_id = self.judge_id

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,11}$',
                                 message="Факс должен иметь формат: '+999999999'. До 11 цифр и символ +")

    name = models.CharField(max_length=256,verbose_name='Наименование заявления')
    court = models.CharField(max_length=256,verbose_name='Арбитражный суд')
    plaintfill = models.CharField(max_length=256,verbose_name='Представитель')
    address = models.CharField(max_length=256,verbose_name='Адрес')
    fax = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday = models.DateField(verbose_name='Дата рождения')

    plaintfill_representative = models.CharField(max_length=256,verbose_name='Представитель')
    address_representative = models.CharField(max_length=256,verbose_name='Адрес')
    fax_representative = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email_representative = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday_representative = models.DateField(verbose_name='Дата рождения')

    defendant = models.CharField(max_length=256,verbose_name='Представитель')
    address_defendant = models.CharField(max_length=256,verbose_name='Адрес')
    fax_defendant = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email_defendant = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday_defendant = models.DateField(verbose_name='Дата рождения')

    assign_date = models.DateField(blank=True, null=True)

    date = models.DateField(default=django.utils.timezone.now,verbose_name='Дата')
    files = models.ManyToManyField(File,verbose_name='Приложение')
    claim_file = models.ForeignKey(ClaimFile, blank=True, null=True)

    claim_body = models.TextField(verbose_name='Исковое заявление')
    claim_request  = models.TextField(verbose_name='Прошу')

    classification = models.ForeignKey(Classification, blank=True, null=True)


class StatusClaimHistory(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    reason = models.TextField(verbose_name='На основании чего')
    new_status = models.ForeignKey(StatusClaim, null=True, related_name='new_status',verbose_name='Новый статус')
    old_status = models.ForeignKey(StatusClaim, null=True, related_name='old_status',verbose_name='Текущий статус')

    claim = models.ForeignKey(Claim)


class Setting(models.Model):
    ENABLE_AUTO_CLASSIFICATION = 1
    JUDGE_DAILY_CLAIM_COUNT = 2

    value = models.CharField(max_length=256)

    def getValueById(id):
        return Setting.objects.filter(id=id).get().value

administrator/views.py
import datetime
from base64 import decode

from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from administrator.tools import getJudgeLoad

from administrator.forms import ClassificationForm, EmployeeForm, UserEmployeeForm, EmployeeCharacteristicsForm
from administrator.models import EmployeeCharacteristic
from user.models import Employee, Role, Setting, Classification
from user.tools import checkEmployee
from manager.tools import getPath, getChildClassifications
from administrator.tools import isDeletableClassifiaction, getDeleteClassifications


@login_required(login_url='login_page')
def employees(request):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        if request.method == 'GET':
            empl = Employee.objects.all()
            return render(request, 'employees.html', {'employees': empl})
    else:
        return JsonResponse({'error': 'permission denied'})


@login_required(login_url='login_page')
def employee_update(request, employee_id):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        if request.method == 'GET':
            employee = Employee.objects.get(id=employee_id)
            form_employee = EmployeeForm(instance=employee)
            employee.user.password = ""
            form_user_employee = UserEmployeeForm(instance=employee.user)
            return render(request, 'employee_update_form.html',
                          {'form_employee': form_employee, 'form_user_employee': form_user_employee,
                           'employee_id': employee_id})
        elif request.method == 'POST':
            employee = Employee.objects.get(id=employee_id)
            user = employee.user
            fio = request.POST['fio']
            username = request.POST['username']
            password = request.POST['password']
            phone = request.POST['phone']
            email = request.POST['email']
            role_id = request.POST['role']
            classification = request.POST.getlist('classification', [])
            employee.fio = fio
            role = Role.objects.get(id=role_id)
            employee.role = role
            employee.classification = classification
            employee.phone = phone
            user.username = username
            user.save(update_fields=['password'])
            user.email = email
            form_user_employee = UserEmployeeForm(request.POST, instance=user)
            form_employee = EmployeeForm(request.POST, instance=employee)
            if form_employee.is_valid() and form_user_employee.is_valid():
                form_employee.save()
                form_user = form_user_employee.save(commit=False)
                form_user.password = make_password(password)
                form_user.save()
                form_user_employee.save()
                return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'error',
                                     'message_employee': str(form_employee.errors.as_ul()),
                                     'message_user_employee': str(form_user_employee.errors.as_ul())})


@login_required(login_url='login_page')
def employees_characteristics(request):
    if checkEmployee(request.user, Role.ROLE_ADMIN) or checkEmployee(request.user, Role.ROLE_MANAGER):
        if request.method == 'GET':
            employees_characteristics = EmployeeCharacteristic.objects.all()
            result = getJudgeLoad(employees_characteristics)
            return render(request, 'employee_characteristics_admin.html', {'employees': result})
    else:
        return JsonResponse({'error': 'permission denied'})


@login_required(login_url='login_page')
def settings(request):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        if request.method == 'GET':
            enable_value = Setting.getValueById(Setting.ENABLE_AUTO_CLASSIFICATION)
            if (enable_value == '1'):
                enable = True
            else:
                enable = False
            daily_count = Setting.getValueById(Setting.JUDGE_DAILY_CLAIM_COUNT)
            return render(request, 'setting.html',
                          {
                              'enable_auto': enable,
                              'setting_enable_id': Setting.ENABLE_AUTO_CLASSIFICATION,
                              'daily_count': daily_count,
                              'daily_count_id': Setting.JUDGE_DAILY_CLAIM_COUNT
                          })
    else:
        return JsonResponse({'error': 'permission denied'})


def settings_update(request, setting_id):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        setting = Setting.objects.filter(id=setting_id).get()
        setting.value = request.POST['value']
        setting.save()
        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'error'})


@csrf_exempt
@login_required(login_url='login_page')
def classification_list(request):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        if request.method == 'GET':
            form = ClassificationForm()
            classifications = getChildClassifications()
            result = []
            for classification in list(classifications):
                result.append({
                    'item': classification,
                    'path': getPath(classification),
                })
            return render(request, 'classifications.html', {
                'classifications': result,
                'form': form,
                'remove_classifications': getDeleteClassifications()
            })
        elif request.method == 'POST':
            classification = Classification()
            form = ClassificationForm(request.POST, instance=classification)
            if form.is_valid():
                form.save()
                return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'error', 'message': str(form.errors.as_ul())})
    else:
        return JsonResponse({'error': 'permission denied'})


@csrf_exempt
@login_required(login_url='login_page')
def classification_delete(request):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        if request.method == "POST":
            classification_ids = request.POST.getlist("delete_classification_ids", [])
            if len(classification_ids) == 0:
                return JsonResponse({'status': 'error', 'message': 'Выберите классы'})
            classifications = Classification.objects.filter(id__in=classification_ids)
            result_error = ''
            for classification in classifications:
                if isDeletableClassifiaction(classification):
                    classification.delete()
                else:
                    result_error = result_error + "</br>" + classification.name + " невозможно удалить"
            if result_error == '':
                return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'error', 'message': result_error})

    else:
        return JsonResponse({'error': 'permission denied'})


def employee_characteristics_create(request):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        if request.method == "POST":
            employee = request.POST['employee']
            qualification = request.POST['qualification']
            employee_characteristics = EmployeeCharacteristic()
            employee = Employee.objects.get(id=employee)
            employee_characteristics.date_finish = datetime.datetime.strptime(request.POST['date_finish'],
                                                                              '%d.%m.%Y').strftime('%Y-%m-%d')
            employee_characteristics.date_start = datetime.datetime.strptime(request.POST['date_start'],
                                                                             '%d.%m.%Y').strftime('%Y-%m-%d')
            employee_characteristics.employee = employee
            employee_characteristics.qualification = qualification
            employee_form = EmployeeCharacteristicsForm(request.POST, instance=employee_characteristics)
            if employee_characteristics.date_finish < employee_characteristics.date_start:
                employee_form.add_error(
                    'date_start',
                    'Дата конца отпуска не может быть раньше начала'
                )

            if employee_form.is_valid():
                employee_form.save()
                return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'error', 'message': str(employee_form.errors.as_ul())})
        elif request.method == "GET":
            employee_form = EmployeeCharacteristicsForm()
            return render(request, 'employee_characteristics_create.html', {'employee_form': employee_form})
    else:
        return JsonResponse({'error': 'permission denied'})


def employee_delete(request, employee_id):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        employee = Employee.objects.get(id=employee_id)
        employee.delete()
        return redirect(to='employees')
    else:
        return JsonResponse({'error': 'permission denied'})

administrator/templates/classifications.html
{% extends "base.html" %}
{% block title %}Классы заявлений{% endblock %}
{% block content %}
    <button data-toggle="modal"
            data-target="#myModal" class="btn btn-success"
            style="margin: 10px">Добавить
    </button>
    <button data-toggle="modal"
            data-target="#deleteModal" class="btn btn-danger"
            style="margin: 10px">Удалить
    </button>
    {% include 'show_classifications.html' %}
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Добавление класса заявления</h4>
                    <button id="save" href="{% url 'classification_list' %}" class="btn btn-success">Сохранить
                    </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        Закрыть
                    </button>
                    <div id="result">
                    </div>
                </div>
                <div class="modal-body">
                    {% load bootstrap3 %}
                    <form id="add_classification" method="post" action="{% url 'classification_list' %}">
                        {% bootstrap_form form %}
                    </form>
                </div>
            </div>

        </div>
    </div>
    <div class="modal fade" id="deleteModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Удаления класса</h4>
                    <button id="delete" href="{% url 'classification_delete' %}" class="btn btn-success">Удалить
                    </button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        Закрыть
                    </button>
                    <div id="result_delete">
                    </div>
                </div>
                <div class="modal-body">
                    {% if remove_classifications %}
                        <select id="delete_classes" multiple="multiple" name="delete_classification_ids" size="8"
                                style="margin-left:5%;width: 90% ">
                            {% for classification in remove_classifications %}
                                <option value="{{ classification.id }}">
                                    {{ classification.name }}
                                </option>
                            {% endfor %}
                        </select>
                    {% else %}
                        Классов для удаления нет
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $("#delete_classes").treeMultiselect({hideSidePanel: true});

        $("#save").click(function () {
            var form = $("#add_classification");
            $.ajax({
                type: "POST",
                url: form.attr('action'),
                data: form.serialize(),
                success: function (response) {
                    result_div = $('#result');
                    if (response.status == 'success') {
                        window.location.reload();
                    } else {
                        result_div.html("<div class='alert alert-danger'>" + response.message + "</div>")

                    }

                }
            });
        });
        $("#delete").click(function () {
            $.ajax({
                type: "POST",
                url: $('#delete').attr('href'),
                data: $('#delete_classes').serialize(),
                success: function (response) {
                    result_div = $('#result_delete');
                    if (response.status == 'success') {
                        window.location.reload();
                    } else {
                        result_div.html("<div class='alert alert-danger'>" + response.message + "</div>")

                    }

                }
            });
        });



    </script>
{% endblock %}

administrator/templates/employee_characteristics_admin.html
{% extends "base.html" %}
{% block title %}Пользователи{% endblock %}
{% block content %}
    {% load staticfiles %}
    <div id="characteristics" class="tab-pane fade in active">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="tab-content-btn">
                        {% if user.employee.role.sys_name == 'ROLE_ADMIN' %}
                            <a data-toggle="modal" href="{% url 'employee_characteristics_create' %}"
                               data-target="#myModal" class="btn btn-update">Создать</a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-12">
                    <table>
                        <tr class="border_bottom">
                            <td class="edit">

                            </td>
                            <td class="name cell">
                                ФИО
                            </td>
                            <td class="holiday-start cell">
                                Дата начала отпуска
                            </td>
                            <td class="holiday-stop cell">
                                Дата конца отпуска
                            </td>
                            <td class="qualification cell">
                                Квалификация
                            </td>
                        </tr>
                        {% for empl in employees %}
                            <tr class="border_bottom">
                                <td class="edit">
{#                                    <a href="" class="icon-button" data-toggle="modal"#}
{#                                       data-target="#change-judge"><img src="{% static 'icon/edit.svg'%}"></a>#}
                                </td>
                                <td class="name cell">
                                    {{ empl.item.employee.fio }}
                                </td>
                                <td class="holiday-start cell">
                                    {{ empl.item.date_start }}
                                </td>
                                <td class="holiday-stop cell">
                                    {{ empl.item.date_finish }}
                                </td>
                                <td class="qualification cell">
                                    {{ empl.item.qualification }}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">


        </div>
    </div>
{% endblock %}
{% block js %}

    <script type="text/javascript">

        $(document).ready(function () {

            $('[data-toggle="modal"]').click(function (e) {
                e.preventDefault();
                var url = $(this).attr('href');
                $.get(url, function (data) {
                    $('.modal-dialog').html(data);
                    $('#myModal').modal('show');
                });
            });

        });

    </script>
{% endblock %}

administrator/templates/employee_characteristics_create.html
{{ employee_form.media }}
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Создать характеристику</h4>
        <p>
            <button id="employee_char_create_submit" class="btn btn-success">Сохранить</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Закрыть</button>
        </p>
        <div id="result">
        </div>
    </div>

    <div class="modal-body">

        {% load bootstrap3 %}
        <form id="employee_char_create_form" method="post" action="{% url 'employee_characteristics_create' %}">
            {% csrf_token %}
            {{ employee_form.errors }}
            {% bootstrap_form employee_form %}
        </form>
    </div>
</div>

<script type="text/javascript">
    $("#employee_char_create_submit").click(function () {
        var form = $("#employee_char_create_form");
        $.ajax({
            type: "POST",
            url: form.attr('action'),
            data: form.serialize(),
            success: function (response) {
                result_div = $('#result');
                if (response.status == 'success') {
                    window.location.reload();
                } else {
                    result_div.html("<div class='alert alert-danger'>" + response.message + "</div>")
                }

            }
        });
    });
</script>

administrator/templates/employee_update_form.html
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Обновить информацию сотрудника</h4>
        <p>
            <button id="employee_update_submit" class="btn btn-success">Сохранить</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal" >Закрыть</button>
        </p>
        <div id="result">
        </div>
    </div>

    <div class="modal-body">

        {% load bootstrap3 %}
        <form id="employee_update_form" method="post" action="{% url 'employee_update' employee_id %}">
            {% csrf_token %}
            {{ form_employee.errors }}
            {{ form_user_employee.errors }}
            {% bootstrap_field form_employee.fio %}
            {% bootstrap_field form_user_employee.username %}
            {% bootstrap_field form_user_employee.password %}
            {% bootstrap_field form_employee.phone %}
            {% bootstrap_field form_user_employee.email %}
            {% bootstrap_field form_employee.role %}
            {% bootstrap_field form_employee.classification %}
        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var gr = $('.form-group');
        if ($('#id_role').children('option:selected').html() == "Судья"){
            $('.form-group').children('#id_classification').parent().show()
        }
        else {
            $('.form-group').children('#id_classification').parent().hide()
        }
    });

    $(document).on('change', '#id_role', function () {
        console.log("Hell")
        var gr = $('.form-group');
        if ($('#id_role').children('option:selected').html() == "Судья"){
            $('.form-group').children('#id_classification').parent().show()
        }
        else{
            $('.form-group').children('#id_classification').parent().hide()
        }

    });

    $("#employee_update_submit").click(function () {
        var form = $("#employee_update_form");
        $.ajax({
            type: "POST",
            url: form.attr('action'),
            data: form.serialize(),
            success: function (response) {
                result_div = $('#result');
                if (response.status == 'success') {
                    window.location.reload();
                } else {
                    if (response.message_employee !== ""){
                        result_div.html("<div class='alert alert-danger'>" + response.message_employee + "</div>")
                    }else{
                        if (response.message_user_employee !== ""){
                            result_div.html("<div class='alert alert-danger'>" + response.message_user_employee + "</div>")
                        }
                    }

                }

            }
        });
    });
</script>