api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from api import views

urlpatterns = [
    url(r'^data$', views.getData, name='data_api'),
    url(r'^(?P<judge_id>\d+)/(?P<claim_id>\d+)$', views.setClaimToJudge, name='set_claim_to_judge')
]

robo/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from robo import settings

urlpatterns = [
                  url(r'^administrator/', include('administrator.urls')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^user/', include('user.urls')),
                  url(r'^', include('user.urls')),
                  url(r'^manager/', include('manager.urls')),
                  url(r'^judge/', include('judge.urls')),
                  url(r'^api/', include('api.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from user import views

urlpatterns = [
    url(r'^$', views.default, name='default'),
    url(r'^claims$', views.list_claims, name='list_claims'),
    url(r'^login$', views.login_page, name='login_page'),
    url(r'^logout$', views.make_logout, name='logout'),
    url(r'^claim/add$', views.add_claim, name='add_claim'),
    # url(r'^claim/(?P<claim_id>\d+)$', views.claim_page, name='claim_page'),
    url(r'^claim/upload-file$', views.add_claim_file, name='add_claim_file')


]

user/models.py
import datetime
from datetime import datetime as date_now

import django
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


# Create your models here.
class File(models.Model):
    name = models.CharField(max_length=128)
    file = models.FileField(upload_to='docs/')

class ClaimFile(models.Model):
    name = models.CharField(max_length=128)
    file = models.FileField(upload_to='claims/')

class Classification(models.Model):
    def __str__(self):
        return self.name

    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, unique=True)
    enable = models.BooleanField(default=True)
    difficult = models.PositiveSmallIntegerField(default=1)

class Role(models.Model):
    ROLE_MANAGER = 1
    ROLE_JUDGE = 2
    ROLE_ADMIN = 3

    def __str__(self):
        return self.name

    name = models.CharField(max_length=256, unique=True)
    sys_name = models.CharField(max_length=256, unique=True)


class Profile(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User)


class Employee(models.Model):
    def __str__(self):
        return ' / '.join([self.fio, self.role.name])

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    user = models.OneToOneField(User, verbose_name="Пользователь")
    fio = models.CharField(max_length=256, verbose_name='ФИО')
    phone = models.CharField(max_length=256, verbose_name='Телефон')
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True, verbose_name='Роль')
    classification = models.ManyToManyField(Classification, blank=True, null=True, verbose_name='Классификация')


class StatusClaim(models.Model):
    def __str__(self):
        return self.name

    STATUS_ACCEPT = 1
    STATUS_RETURN = 2
    STATUS_ARCHIVE = 3
    STATUS_STOP = 4
    STATUS_REJECT = 5
    STATUS_GRANT = 6
    STATUS_GRANT_PARTIALLY = 7
    STATUS_PROCESSING = 8

    @staticmethod
    def getClaimNotFinishedStatuses():
        return [StatusClaim.STATUS_STOP, StatusClaim.STATUS_ACCEPT]

    name = models.TextField(max_length=256)


class Claim(models.Model):
    def __str__(self):
        return self.name

    user = models.ForeignKey(Profile, null=True)
    judge = models.ForeignKey(Employee, blank=True, null=True)
    status = models.ForeignKey(StatusClaim, blank=True, null=True, default=StatusClaim.STATUS_PROCESSING, editable=False)

    __previous_judge_id = None

    def __init__(self, *args, **kwargs):
        super(Claim, self).__init__(*args, **kwargs)
        self.__previous_judge_id = self.judge_id

    # Сохранение даты назначения на судью
    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.judge_id != None and self.judge_id != self.__previous_judge_id:
            self.assign_date = date_now.now().date()

        super(Claim, self).save(force_insert, force_update, *args, **kwargs)
        self.__previous_judge_id = self.judge_id

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,11}$',
                                 message="Факс должен иметь формат: '+999999999'. До 11 цифр и символ +")

    name = models.CharField(max_length=256,verbose_name='Наименование заявления')
    court = models.CharField(max_length=256,verbose_name='Арбитражный суд')
    plaintfill = models.CharField(max_length=256,verbose_name='Представитель')
    address = models.CharField(max_length=256,verbose_name='Адрес')
    fax = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday = models.DateField(verbose_name='Дата рождения')

    plaintfill_representative = models.CharField(max_length=256,verbose_name='Представитель')
    address_representative = models.CharField(max_length=256,verbose_name='Адрес')
    fax_representative = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email_representative = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday_representative = models.DateField(verbose_name='Дата рождения')

    defendant = models.CharField(max_length=256,verbose_name='Представитель')
    address_defendant = models.CharField(max_length=256,verbose_name='Адрес')
    fax_defendant = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email_defendant = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday_defendant = models.DateField(verbose_name='Дата рождения')

    assign_date = models.DateField(blank=True, null=True)

    date = models.DateField(default=django.utils.timezone.now,verbose_name='Дата')
    files = models.ManyToManyField(File,verbose_name='Приложение')
    claim_file = models.ForeignKey(ClaimFile, blank=True, null=True)

    claim_body = models.TextField(verbose_name='Исковое заявление')
    claim_request  = models.TextField(verbose_name='Прошу')

    classification = models.ForeignKey(Classification, blank=True, null=True)


class StatusClaimHistory(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    reason = models.TextField(verbose_name='На основании чего')
    new_status = models.ForeignKey(StatusClaim, null=True, related_name='new_status',verbose_name='Новый статус')
    old_status = models.ForeignKey(StatusClaim, null=True, related_name='old_status',verbose_name='Текущий статус')

    claim = models.ForeignKey(Claim)


class Setting(models.Model):
    ENABLE_AUTO_CLASSIFICATION = 1
    JUDGE_DAILY_CLAIM_COUNT = 2

    value = models.CharField(max_length=256)

    def getValueById(id):
        return Setting.objects.filter(id=id).get().value

user/forms.py
from datetimewidget.widgets import DateWidget
from django import forms
from django.core.validators import RegexValidator
from django.forms import ModelForm
from user.models import Claim, StatusClaimHistory, StatusClaim
from user.widgets import MultiFileInput
from django.db.models import Q
from django.core import validators


class LoginForm(forms.Form):
    username = forms.CharField(label='Логин', max_length=64)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

class StatusClaimHistoryForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(StatusClaimHistoryForm, self).__init__(*args, **kwargs)
        ids = [StatusClaim.STATUS_GRANT_PARTIALLY, StatusClaim.STATUS_GRANT, StatusClaim.STATUS_REJECT]
        self.fields['new_status'].queryset = StatusClaim.objects.filter(~Q(id=self.instance.claim.status_id))

    class Meta:
        model = StatusClaimHistory
        fields = '__all__'
        exclude = ['date', 'old_status', 'claim']

class FirstStatusClaimHistoryForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(FirstStatusClaimHistoryForm, self).__init__(*args, **kwargs)
        ids = [StatusClaim.STATUS_GRANT_PARTIALLY, StatusClaim.STATUS_GRANT, StatusClaim.STATUS_REJECT]
        self.fields['new_status'].queryset = StatusClaim.objects.filter(~Q(id=self.instance.claim.status_id)).exclude(id__in=ids)

    class Meta:
        model = StatusClaimHistory
        fields = '__all__'
        exclude = ['date', 'old_status', 'claim']


class SecondStatusClaimHistoryForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SecondStatusClaimHistoryForm, self).__init__(*args, **kwargs)
        ids = [StatusClaim.STATUS_GRANT_PARTIALLY, StatusClaim.STATUS_GRANT, StatusClaim.STATUS_REJECT]
        self.fields['new_status'].queryset = StatusClaim.objects.filter(~Q(id=self.instance.claim.status_id)).filter(id__in=ids)

    class Meta:
        model = StatusClaimHistory
        fields = '__all__'
        exclude = ['date', 'old_status', 'claim']


class ClaimForm(ModelForm):
    class Meta:
        model = Claim
        fields = '__all__'
        exclude = ['judge', 'user', 'status', 'classification', 'files', 'assign_date', 'claim_file']
        widgets = {
            'date_of_birthday': DateWidget(usel10n=True, bootstrap_version=3),
            'date_of_birthday_defendant': DateWidget(usel10n=True, bootstrap_version=3),
            'date_of_birthday_representative': DateWidget(usel10n=True, bootstrap_version=3),
            'date': DateWidget(usel10n=True, bootstrap_version=3)
        }

    list_item = [
        ('Арбитражный суд', 'Арбитражный суд')
    ]
    court = forms.ChoiceField(choices=list_item)

user/views.py
import datetime
import os

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sessions import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.db.models import Q
from docx import Document

from judge.tools import getFactsClaimsId, getClaimCaseHref
from user.tools import generateDocByClaim, checkEmployee
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
from user.forms import LoginForm, ClaimForm, SecondStatusClaimHistoryForm
from user.models import Claim, Profile, File, StatusClaim, StatusClaimHistory, Role, Employee


@login_required(login_url='login_page')
def default(request):
    return render(request, 'base.html')


@login_required(login_url='login_page')
def list_claims(request):
    if request.method == 'GET':
        try:
            u = Profile.objects.get(user=request.user)
        except ObjectDoesNotExist:
            return redirect(to='employees')
        claims = Claim.objects.filter(user=u).filter(~Q(status_id=StatusClaim.STATUS_ARCHIVE))
        return render(request, 'user_claims.html', {'claims': claims})


def login_page(request, error=None):
    if request.user.is_authenticated:
        try:
            us = Profile.objects.get(user_id=request.user)
        except ObjectDoesNotExist:
            return redirect(to='employees')
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect(to='list_claims')
        else:
            lf = LoginForm()
            return render(request, 'login.html', {'login_form': lf,
                                                  'error': error})
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(to='/')
        else:
            data = request.POST.copy()

            lf = LoginForm(initial=data)
            return render(request, 'login.html', {'login_form': lf,
                                                  'error': 'Ошибка авторизации'})


def make_logout(request):
    logout(request)
    return redirect(to='login_page')


@login_required(login_url='login_page')
def add_claim(request):
    if request.user.is_authenticated:
        try:
            us = Profile.objects.get(user_id=request.user)
        except ObjectDoesNotExist:
            return redirect(to='employees')
    if request.method == "POST":
        files = request.FILES.getlist('files')
        claim = Claim()
        claim.user = Profile.objects.get(user_id=request.user)
        claim.fax = request.POST['fax']
        claim.fax_representative = request.POST['fax_representative']
        claim.fax_defendant = request.POST['fax_defendant']

        cf = ClaimForm(request.POST, instance=claim)
        if cf.is_valid():
            cf.save()
            for file in files:
                f = File()
                f.file = file
                f.name = 'test'
                f.save()
                claim.files.add(f)
            claim.save()
            generateDocByClaim(claim)
            cf = ClaimForm(request.POST, instance=claim)
            s = cf.save(commit=False)
            s.date_of_birthday = datetime.datetime.strptime(request.POST['date_of_birthday'],
                                                            '%d.%m.%Y').strftime('%Y-%m-%d')
            s.date_of_birthday_defendant = datetime.datetime.strptime(request.POST['date_of_birthday_defendant'],
                                                                      '%d.%m.%Y').strftime('%Y-%m-%d')
            s.date_of_birthday_representative = datetime.datetime.strptime(
                request.POST['date_of_birthday_representative'],
                '%d.%m.%Y').strftime('%Y-%m-%d')
            s.date = datetime.datetime.strptime(
                request.POST['date'],
                '%d.%m.%Y').strftime('%Y-%m-%d')
            s.save()
            return redirect(to='list_claims')
        else:

            return render(request, 'add_claim.html', {'form': cf})

    elif request.method == "GET":
        form = ClaimForm()
        return render(request, 'add_claim.html', {'form': form})


@csrf_exempt
@login_required(login_url='login_page')
def add_claim_file(request):
    if request.user.is_authenticated and request.method == "POST":
        file = request.FILES.get('file')
        filename = request.POST.get('filename')
        f = File()
        f.file = file
        f.name = filename
        f.save()
        return JsonResponse({id: f.id})
    else:
        raise Exception()


# @login_required(login_url='login_page')
# def claim_page(request, claim_id):
#         if request.method == 'GET':
#             empl = Employee.objects.get(user_id=request.user)
#             claim = Claim.objects.get(judge=empl, id=claim_id)
#             claim_file_path = str(claim.claim_file.file)
#             filename, file_extension = os.path.splitext(claim_file_path)
#             filepath = os.path.join(settings.MEDIA_ROOT, claim_file_path)
#             f = open(filepath, 'rb')
#             content = ''
#             if (claim.claim_file.name not in getFactsClaimsId()):
#                 is_mark = False
#                 if (file_extension == '.docx'):
#                     doc = Document(f)
#                     fullText = []
#                     for para in doc.paragraphs:
#                         fullText.append(para.text)
#                     content = '\n'.join(fullText)
#             else:
#                 is_mark = True
#                 content = getClaimCaseHref(claim.claim_file.name)
#             claim_history = StatusClaimHistory()
#             claim_history.claim_id = claim.id
#             form = SecondStatusClaimHistoryForm(instance=claim_history)
#             form.old_status = claim.status
#             form.new_status = claim.status
#             return render(request, 'claim_page.html', {
#                 'is_mark': is_mark,
#                 'content': content,
#                 'form': form,
#                 'claim': claim
#             })

user/templates/add_claim.html
{% extends "base.html" %}
{% block title %}Добавить заявление{% endblock %}
{% block content %}
{{ form.media }}
{% load bootstrap3 %}
{# Display a form #}

{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/fileinput.min.css' %}" xmlns="http://www.w3.org/1999/html">


<script type="text/javascript" src="{% static 'js/fileinput.min.js' %}">
</script>
<script type="text/javascript" src="{% static 'js/ru.js' %}">
</script>

<form method="post" action="{% url 'add_claim' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            {% bootstrap_field form.name %}
            <h4>Истец</h4>

            {% bootstrap_field form.plaintfill %}
            {% bootstrap_field form.address %}
            {% bootstrap_field form.fax %}
            {% bootstrap_field form.email %}
            {% bootstrap_field form.date_of_birthday %}
        </div>
        <div class="col-md-4">
            {% bootstrap_field form.court %}
            <h4>Представитель истца</h4>

            {% bootstrap_field form.plaintfill_representative %}
            {% bootstrap_field form.address_representative %}
            {% bootstrap_field form.fax_representative %}
            {% bootstrap_field form.email_representative %}
            {% bootstrap_field form.date_of_birthday_representative %}
        </div>
        <div class="col-md-4">
            {% bootstrap_field form.date %}

            <h4>Ответчик</h4>
            {% bootstrap_field form.defendant %}
            {% bootstrap_field form.address_defendant %}
            {% bootstrap_field form.fax_defendant %}
            {% bootstrap_field form.email_defendant %}
            {% bootstrap_field form.date_of_birthday_defendant %}

        </div>
    </div>
    <div class="row">
        {% bootstrap_field form.claim_body %}
    </div>
    <div class="row">
        {% bootstrap_field form.claim_request %}
    </div>

    <label class="control-label">Добавить приложение</label>
    <div class="row">
        <div class="col-md-9 ">
            <input id="id_files" name="files" type="file" class="file file-loading"
                   data-show-preview="false"
                   data-allowed-file-extensions='["docx", "txt","doc","pdf"]'>
        </div>
        <div class="col-md-2 col-md-offset-1">
            {% buttons %}
            <button type="submit" class="btn btn-success btn-lg">
                Отправить
            </button>
            {% endbuttons %}
        </div>
    </div>

    <div style="padding:20px;">

    </div>
    <ul id='claim_apply'>
    </ul>
</form>
<script type="text/javascript">
$("#id_files").fileinput({
    language: "ru",
    showUpload: false,
});




</script>
{% endblock %}

user/templates/login.html
{% extends "base.html" %}
{% block title %}Вход{% endblock %}
{% block content %}
<div class="loginmodal-container">
        <h1>Войти в аккаунт</h1><br>
<form method="post" action="{% url 'login_page' %}" class="form-signin">
    {% csrf_token %}
    {% if error %}
    {{ error }}
    {% endif %}
    {{ login_form.as_p }}
    <input class="btn btn-success" type="submit" value="Войти">
</form>
        <div class="login-help"></div>
</div>

{% endblock %}

user/templates/user_claims.html
{% extends "base.html" %}
{% block title %}Заявления{% endblock %}
{% block content %}
    {% load staticfiles %}
    <div id="statement-user" class="tab-pane fade in active">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="tab-content-btn">
                        <a href="{{ request.url }}" class="btn btn-update">
                            Обновить
                        </a>
                    </div>
                </div>
                <div class="col-md-12">
                    <table>
                        <tr>
                            <td class="edit cell"></td>
                            <td class="name cell">Название</td>
                            <td class="class cell">Класс</td>
                            <td class="date cell">Дата</td>
                            <td class="status cell">Статус</td>
                            <td class="remove cell"></td>
                            <td>Документы</td>
                        </tr>
                        {% for claim in claims %}
                            <tr class="border_bottom">
                                <td class="edit cell">
                                </td>
                                <td class="name cell">
                                    <a href="{% url 'claim_page' claim.id %}">
                                        Заявление {{ claim.id }}
                                    </a>
                                </td>
                                <td class="class cell">
                                    {% if claim.classification == None %}
                                        Не определено
                                    {% else %}
                                        {{ claim.classification }}
                                    {% endif %}

                                </td>
                                <td class="date cell">
                                    {{ claim.date }}
                                </td>
                                <td class="status cell">
                                    {{ claim.status }}
                                </td>

                                <td class="remove cell">
                                </td>
                                <td>
                                    {% if claim.claim_file.file %}
                                        <a href="media/{{ claim.claim_file.file }}" target="_blank" class="glyphicon glyphicon-download"></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}