api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from api import views

urlpatterns = [
    url(r'^data$', views.getData, name='data_api'),
    url(r'^(?P<judge_id>\d+)/(?P<claim_id>\d+)$', views.setClaimToJudge, name='set_claim_to_judge')
]

manager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from manager import views

urlpatterns = [
    url(r'^claims/$', views.claims, name='manager_claims'),
    url(r'^classifications/$', views.classifications, name='manager_classifications'),
    url(r'^change-class/(?P<judge_id>\d+)$', views.change_judge_class, name='change_judge_class'),
    url(r'^change-claim/(?P<claim_id>\d+)$', views.change_claim, name='change_claim'),
    url(r'^list/$', views.judge_list, name='judge_list'),
    url(r'^employees_characteristics_manager/$', views.employees_characteristics, name='employees_characteristics_manager'),
    url(r'^employee_characteristics_create_manager/$', views.employee_characteristics_create,
        name='employee_characteristics_create_manager'),
]

robo/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from robo import settings

urlpatterns = [
                  url(r'^administrator/', include('administrator.urls')),
                  url(r'^admin/', admin.site.urls),
                  url(r'^user/', include('user.urls')),
                  url(r'^', include('user.urls')),
                  url(r'^manager/', include('manager.urls')),
                  url(r'^judge/', include('judge.urls')),
                  url(r'^api/', include('api.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/models.py
from django.db import models

# Create your models here.

user/models.py
import datetime
from datetime import datetime as date_now

import django
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


# Create your models here.
class File(models.Model):
    name = models.CharField(max_length=128)
    file = models.FileField(upload_to='docs/')

class ClaimFile(models.Model):
    name = models.CharField(max_length=128)
    file = models.FileField(upload_to='claims/')

class Classification(models.Model):
    def __str__(self):
        return self.name

    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=256, unique=True)
    enable = models.BooleanField(default=True)
    difficult = models.PositiveSmallIntegerField(default=1)

class Role(models.Model):
    ROLE_MANAGER = 1
    ROLE_JUDGE = 2
    ROLE_ADMIN = 3

    def __str__(self):
        return self.name

    name = models.CharField(max_length=256, unique=True)
    sys_name = models.CharField(max_length=256, unique=True)


class Profile(models.Model):
    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User)


class Employee(models.Model):
    def __str__(self):
        return ' / '.join([self.fio, self.role.name])

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    user = models.OneToOneField(User, verbose_name="Пользователь")
    fio = models.CharField(max_length=256, verbose_name='ФИО')
    phone = models.CharField(max_length=256, verbose_name='Телефон')
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True, verbose_name='Роль')
    classification = models.ManyToManyField(Classification, blank=True, null=True, verbose_name='Классификация')


class StatusClaim(models.Model):
    def __str__(self):
        return self.name

    STATUS_ACCEPT = 1
    STATUS_RETURN = 2
    STATUS_ARCHIVE = 3
    STATUS_STOP = 4
    STATUS_REJECT = 5
    STATUS_GRANT = 6
    STATUS_GRANT_PARTIALLY = 7
    STATUS_PROCESSING = 8

    @staticmethod
    def getClaimNotFinishedStatuses():
        return [StatusClaim.STATUS_STOP, StatusClaim.STATUS_ACCEPT]

    name = models.TextField(max_length=256)


class Claim(models.Model):
    def __str__(self):
        return self.name

    user = models.ForeignKey(Profile, null=True)
    judge = models.ForeignKey(Employee, blank=True, null=True)
    status = models.ForeignKey(StatusClaim, blank=True, null=True, default=StatusClaim.STATUS_PROCESSING, editable=False)

    __previous_judge_id = None

    def __init__(self, *args, **kwargs):
        super(Claim, self).__init__(*args, **kwargs)
        self.__previous_judge_id = self.judge_id

    # Сохранение даты назначения на судью
    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if self.judge_id != None and self.judge_id != self.__previous_judge_id:
            self.assign_date = date_now.now().date()

        super(Claim, self).save(force_insert, force_update, *args, **kwargs)
        self.__previous_judge_id = self.judge_id

    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,11}$',
                                 message="Факс должен иметь формат: '+999999999'. До 11 цифр и символ +")

    name = models.CharField(max_length=256,verbose_name='Наименование заявления')
    court = models.CharField(max_length=256,verbose_name='Арбитражный суд')
    plaintfill = models.CharField(max_length=256,verbose_name='Представитель')
    address = models.CharField(max_length=256,verbose_name='Адрес')
    fax = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday = models.DateField(verbose_name='Дата рождения')

    plaintfill_representative = models.CharField(max_length=256,verbose_name='Представитель')
    address_representative = models.CharField(max_length=256,verbose_name='Адрес')
    fax_representative = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email_representative = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday_representative = models.DateField(verbose_name='Дата рождения')

    defendant = models.CharField(max_length=256,verbose_name='Представитель')
    address_defendant = models.CharField(max_length=256,verbose_name='Адрес')
    fax_defendant = models.CharField(max_length=256,verbose_name='Телефон',validators=[phone_regex])
    email_defendant = models.EmailField(max_length=256,verbose_name='Адрес электронной почты')
    date_of_birthday_defendant = models.DateField(verbose_name='Дата рождения')

    assign_date = models.DateField(blank=True, null=True)

    date = models.DateField(default=django.utils.timezone.now,verbose_name='Дата')
    files = models.ManyToManyField(File,verbose_name='Приложение')
    claim_file = models.ForeignKey(ClaimFile, blank=True, null=True)

    claim_body = models.TextField(verbose_name='Исковое заявление')
    claim_request  = models.TextField(verbose_name='Прошу')

    classification = models.ForeignKey(Classification, blank=True, null=True)


class StatusClaimHistory(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    reason = models.TextField(verbose_name='На основании чего')
    new_status = models.ForeignKey(StatusClaim, null=True, related_name='new_status',verbose_name='Новый статус')
    old_status = models.ForeignKey(StatusClaim, null=True, related_name='old_status',verbose_name='Текущий статус')

    claim = models.ForeignKey(Claim)


class Setting(models.Model):
    ENABLE_AUTO_CLASSIFICATION = 1
    JUDGE_DAILY_CLAIM_COUNT = 2

    value = models.CharField(max_length=256)

    def getValueById(id):
        return Setting.objects.filter(id=id).get().value

manager/forms.py
from django.forms import ModelForm

from user.models import Claim, Employee, Role

class ClaimSettingForm(ModelForm):
    def __init__(self, *args,**kwargs):
        super(ClaimSettingForm, self).__init__( *args,**kwargs)
        self.fields['judge'].queryset = Employee.objects.filter(role=Role.objects.get(sys_name='ROLE_JUDGE'))

    class Meta:
        model = Claim
        fields = ['judge', 'classification']

manager/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import datetime
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from administrator.forms import EmployeeCharacteristicsForm
from administrator.models import EmployeeCharacteristic
from administrator.tools import getJudgeLoad
from manager.forms import ClaimSettingForm
from user.models import Claim, Classification, Employee, Role
from user.tools import checkEmployee
from manager.tools import getPath, getChildClassifications
from django.views.decorators.csrf import csrf_exempt


@login_required(login_url='login_page')
def claims(request):
    if checkEmployee(request.user, Role.ROLE_MANAGER):
        if request.method == 'GET':
            claims = Claim.objects.filter(Q(classification=None) | Q(judge=None))
            return render(request, 'manager_claims.html',{'claims': claims})

    else:
        return JsonResponse({'error': 'permission denied'})


@login_required(login_url='login_page')
def classifications(request):
    if checkEmployee(request.user, Role.ROLE_MANAGER):
        if request.method == 'GET':
            classifications = getChildClassifications()
            result = []
            for classification in list(classifications):
                result.append({
                    'item': classification,
                    'path': getPath(classification),
                })
            return render(request, 'classifications_help.html',{'classifications': result})
    else:
        return JsonResponse({'error': 'permission denied'})


@login_required(login_url='login_page')
def claim_page(request, claim_id):
    if checkEmployee(request.user, Role.ROLE_MANAGER):
        if request.method == 'GET':
            claim = Claim.objects.filter(id=claim_id).values()
            if not list(claim):
                return JsonResponse({'error': 'Claim is not exist or claim is not your'})
            role = Role.objects.get(name='Судья')
            judges = Employee.objects.filter(role=role).values()
            return JsonResponse({'result': {'claims': list(claim), 'judges': list(judges)}})
    else:
        return JsonResponse({'error': 'permission denied'})


@csrf_exempt
@login_required(login_url='login_page')
def change_judge_class(request, judge_id):
    if checkEmployee(request.user, Role.ROLE_MANAGER):
        judge = Employee.objects.get(id=judge_id, role=Role.objects.get(sys_name='ROLE_JUDGE'))
        if request.method == "POST":
            classification_ids = request.POST.getlist("classification_ids", [])
            classifications = Classification.objects.filter(id__in=classification_ids)
            judge.classification = classifications
            judge.save()
            return JsonResponse({'status': 'success'})
        elif request.method == "GET":
            classifications = getChildClassifications()
            result = []
            for classification in list(classifications):
                result.append({
                    'item': classification,
                    'path': getPath(classification),
                    'selected': classification in list(judge.classification.all())
                })
            return render(request, 'change_judge_class.html', {'classifications': result, 'judge': judge})
    else:
        return JsonResponse({'error': 'permission denied'})

@csrf_exempt
@login_required(login_url='login_page')
def change_claim(request, claim_id):
    claim = Claim.objects.get(id=claim_id)
    if claim == None:
        return JsonResponse({'status': 'error'})
    if request.method == "POST":
        form = ClaimSettingForm(request.POST, instance=claim)
        if form.is_valid():
            form.save()
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'error', 'message': str(form.errors.as_ul())})
    elif request.method == "GET":
        form = ClaimSettingForm(instance=claim)
        return render(request, 'change_claim.html', {'form': form})


@login_required(login_url='login_page')
def judge_list(request):
    if checkEmployee(request.user, Role.ROLE_MANAGER):
        if request.method == 'GET':
            judges = Employee.objects.filter(role=Role.objects.get(sys_name='ROLE_JUDGE'))
            return render(request, 'judge_list.html', {'judges': judges})
    else:
        return JsonResponse({'error': 'permission denied'})

@login_required(login_url='login_page')
def employees_characteristics(request):
    if checkEmployee(request.user, Role.ROLE_ADMIN) or checkEmployee(request.user, Role.ROLE_MANAGER):
        if request.method == 'GET':
            employees_characteristics = EmployeeCharacteristic.objects.all()
            result = getJudgeLoad(employees_characteristics)
            return render(request, 'employee_characteristics.html', {'employees': result})
    else:
        return JsonResponse({'error': 'permission denied'})

def employee_characteristics_create(request):
    if checkEmployee(request.user, Role.ROLE_ADMIN):
        if request.method == "POST":
            employee = request.POST['employee']
            qualification = request.POST['qualification']
            employee_characteristics = EmployeeCharacteristic()
            employee = Employee.objects.get(id=employee)
            employee_characteristics.date_finish = datetime.datetime.strptime(request.POST['date_finish'],
                                                                              '%d.%m.%Y').strftime('%Y-%m-%d')
            employee_characteristics.date_start = datetime.datetime.strptime(request.POST['date_start'],
                                                                             '%d.%m.%Y').strftime('%Y-%m-%d')
            employee_characteristics.employee = employee
            employee_characteristics.qualification = qualification
            employee_form = EmployeeCharacteristicsForm(request.POST, instance=employee_characteristics)
            if employee_characteristics.date_finish < employee_characteristics.date_start:
                employee_form.add_error(
                    'date_start',
                    'Дата конца отпуска не может быть раньше начала'
                )

            if employee_form.is_valid():
                employee_form.save()
                return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'error', 'message': str(employee_form.errors.as_ul())})
        elif request.method == "GET":
            employee_form = EmployeeCharacteristicsForm()
            return render(request, 'employee_characteristics_create.html', {'employee_form': employee_form})
    else:
        return JsonResponse({'error': 'permission denied'})

manager/templates/change_claim.html
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title"></h4>
        <p>
            <button id="change_status" class="btn btn-success">Сохранить</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal" >Закрыть</button>
        </p>
        <div id="result">
        </div>
    </div>

    <div class="modal-body">
        {% load bootstrap3 %}
        <form id="change_claim_form" method="post" action="{{ request.path }}">
            {% bootstrap_form form %}
        </form>
    </div>
</div>
<script type="text/javascript">
{#    $('#id_judge').ready(function () {#}
{#        $(this).css('class', 'select2-container form-control select select-primary');#}
{#    });#}
    $('#id_judge').select2({
        width: '100%',
        placeholder: 'Выберите судью ',
        allowClear:true

    });
    $('#id_classification').select2({
        width: '100%',
        placeholder: 'Выберите класс заявления '
    });

    $("#change_status").click(function () {
        var form = $("#change_claim_form");
        $.ajax({
            type: "POST",
            url: form.attr('action'),
            data: form.serialize(),
            success: function (response) {
                result_div = $('#result');
                if (response.status == 'success') {
                    window.location.reload();
                } else {
                    result_div.html("<div class='alert alert-danger'>" + response.message + "</div>")

                }

            }
        });
    });
</script>

manager/templates/change_judge_class.html
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Смена статуса</h4>
        <p>
            <button id="change" href="{% url 'change_judge_class' judge.id %}" class="btn btn-success">Выбрать</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal" >Закрыть</button>
        </p>
        <div id="result">
        </div>
    </div>
    <div class="modal-body">
        <select id="classes" multiple="multiple" name="classification_ids">
            {% for classification in classifications %}
                <option value="{{ classification.item.id }}" data-section="{{ classification.path }}"
                        {% if classification.selected %}
                        selected="selected"
                        {% endif %}
                >
                    {{ classification.item.name }}
                </option>
            {% endfor %}
        </select>
        {% load staticfiles %}
        <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.tree.multiselect.min.js' %}">
        </script>
        <script type="text/javascript">
            var params = {hideSidePanel: true};
            $("#classes").treeMultiselect(params);
        </script>
        <link rel="stylesheet" href="{% static 'css/jquery.tree-multiselect.css' %}">

    </div>
</div>
<script type="text/javascript">
    $("#change").click(function (e) {
        e.preventDefault();

        $.ajax({
            type: "POST",
            url: $('#change').attr('href'),
            data: $('#classes').serialize(),
            success: function (response) {
                result_div = $('#result');
                if (response.status == 'success') {
                    window.location.reload();
                } else {
                    result_div.html("<div class='alert alert-danger'>" + response.message + "</div>")

                }

            }
        });
    });
</script>

manager/templates/classifications_help.html
{% extends "base.html" %}
{% block title %}Справочник заявлений{% endblock %}
{% block content %}
    {% include 'show_classifications.html' %}
{% endblock %}

manager/templates/employee_characteristics.html
{% extends "base.html" %}
{% block title %}Пользователи{% endblock %}
{% block content %}
    {% load staticfiles %}
    <div id="characteristics-manager" class="tab-pane fade in active">
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <table>
                        <tr class="border_bottom">
                            <td class="name cell">
                                ФИО
                            </td>
                            <td class="holiday-start cell">
                                Дата начала отпуска
                            </td>
                            <td class="holiday-stop cell">
                                Дата конца отпуска
                            </td>
                            <td class="qualification cell">
                                Квалификация
                            </td>
                            <td class="load cell">
                                Загруженность
                            </td>
                        </tr>
                        {% for empl in employees %}
                            <tr class="border_bottom">
                                <td class="name cell">
                                    {{ empl.item.employee.fio }}
                                </td>
                                <td class="holiday-start cell">
                                    {{ empl.item.date_start }}
                                </td>
                                <td class="holiday-stop cell">
                                    {{ empl.item.date_finish }}
                                </td>
                                <td class="qualification cell">
                                    {{ empl.item.qualification }}
                                </td>
                                <td class="load cell">
                                    {{ empl.load }}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">


        </div>
    </div>
{% endblock %}
{% block js %}

    <script type="text/javascript">

        $(document).ready(function () {

            $('[data-toggle="modal"]').click(function (e) {
                e.preventDefault();
                var url = $(this).attr('href');
                $.get(url, function (data) {
                    $('.modal-dialog').html(data);
                    $('#myModal').modal('show');
                });
            });

        });

    </script>
{% endblock %}

manager/templates/judge_list.html
{% extends "base.html" %}
{% block title %}Судья{% endblock %}
{% block content %}
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Логин</th>
            <th>Пользователь</th>
            <th>Роль</th>
        </tr>
        </thead>
        <tbody>
        {% for judge in judges %}
            <tr>
                <td>{{ judge.user.username }}
                </td>
                <td>{{ judge.fio }}</td>
                <td>
                    <div class="actions">
                        {{ judge.role.name }}
                        <button data-toggle="modal" href="{% url 'change_judge_class' judge.id %}"
                                data-target="#myModal" class="btn btn-success">Привязать классы
                        </button>
                    </div>
                </td>

            </tr>
        {% empty %}
            Заявлений нет
        {% endfor %}


        </tbody>
    </table>

    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">


        </div>
    </div>
{% endblock %}

{% block js %}

    <script type="text/javascript">

        $(document).ready(function () {

            $('[data-toggle="modal"]').click(function (e) {
                $('.modal-dialog').html('');
                e.preventDefault();
                var url = $(this).attr('href');
                $.get(url, function (data) {
                    $('.modal-dialog').html(data);
                    $('#myModal').modal('show');
                });
            });

        });

    </script>
{% endblock %}

manager/templates/manager_claims.html
{% extends "base.html" %}
{% block title %}Заявления{% endblock %}
{% block content %}
    {% load staticfiles %}
    <div id="statement" class="tab-pane fade in active">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="tab-content-btn">
                        <a href="{{ request.url }}" class="btn btn-update">
                            Обновить
                        </a>
                    </div>
                </div>
                <div class="col-md-12">
                    <table>
                        <tr class="border_bottom">
                            <td class="edit cell">
                                {#                                    <a href="" class="icon-button" data-toggle="modal"#}
                                {#                                       data-target="#class-statement"><img src="{% static 'icon/edit.svg'%}"></a>#}
                            </td>
                            <td class="document cell">
                                Название
                            </td>
                            <td class="doc-class cell">
                                Класс
                            </td>
                            <td class="date cell">
                                Дата
                            </td>
                            <td>
                                Функция
                            </td>

                        </tr>
                        {% for claim in claims %}
                            <tr class="border_bottom">
                                <td class="edit cell">
                                    {#                                    <a href="" class="icon-button" data-toggle="modal"#}
                                    {#                                       data-target="#class-statement"><img src="{% static 'icon/edit.svg'%}"></a>#}
                                </td>
                                <td class="document cell">
                                    <a href="{% url 'claim_page' claim.id %}">Заявление {{ claim.id }}</a>
                                </td>
                                <td class="doc-class cell">
                                    {% if claim.classification == None %}
                                        Не определено
                                    {% else %}
                                        {{ claim.classification }}
                                    {% endif %}
                                </td>
                                <td class="date cell">
                                    {{ claim.date }}
                                </td>
                                <td>
                                    <button data-toggle="modal" href="{% url 'change_claim' claim.id %}"
                                            data-target="#myModal" class="btn btn-success">Назначить
                                    </button>
                                </td>

                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>





    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">


        </div>
    </div>
{% endblock %}

{% block js %}

    <script type="text/javascript">
        $(document).ready(function () {

            $('[data-toggle="modal"]').click(function (e) {
                $('.modal-dialog').html('');
                e.preventDefault();
                var url = $(this).attr('href');
                $.get(url, function (data) {
                    $('.modal-dialog').html(data);
                    $('#myModal').modal('show');
                });
            });

        });

    </script>
{% endblock %}